# Generated by Django 4.0.7 on 2023-08-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gview', '0002_alter_car_id_alter_cat_id_alter_dog_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cat',
            name='name',
        ),
        migrations.AddField(
            model_name='cat',
            name='nickname',
            field=models.CharField(default='Silvester', max_length=200),
        ),
        migrations.AddField(
            model_name='cat',
            name='weight',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gview.breed'),
        ),
    ]
